### ISSUE TITLE
Report hostname changes

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#17] opened 2022-05-29 16:13 UTC
## Summary

We now support resolving the hostnames after a certain number of failures again, using the `-r` flag.

It is beneficial to report the changes and time of them to our users.  For instance:

```
Retried to resolve hostname 2 times
IP address changed from 1.2.3.4 to 5.6.7.8     at 2022-05-29 16:30:21
IP address changed from 5.6.7.8 to 9.10.11.12  at 2022-05-29 17:50:01
```

**Comment by ravsii** [comment] 2023-05-27 17:00
I'll take this one next because it seems small (you're probably tired of my 600 LOC PRs in a 1000 LOC project haha)

One question though, how I can possibly test this? I assume (don't know for sure) the usual `example.com 80` wont work.

@pouriyajamshidi

**Comment by pouriyajamshidi** [comment] 2023-05-27 17:26
> I'll take this one next because it seems small (you're probably tired of my 600 LOC PRs in a 1000 LOC project haha)

haha, not really. 

> One question though, how I can possibly test this? I assume (don't know for sure) the usual example.com 80 wont work.


Good question! I would use Facebook's servers for this one. This is my view and should not be so different for you either:

![image](https://github.com/pouriyajamshidi/tcping/assets/54482226/4b206d7c-0df3-49ae-bd50-6b42ee8d0a86)

I'll run the program like:

```bash
tcping fb.com 443 -r 3
```

And play with `iptables` like this for each resolved IP:

```bash
sudo iptables -A OUTPUT -d 31.13.66.35 -j DROP; sleep 3; sudo iptables -F
```

I have written `retryResolve` function to randomly pick an address and it should avoid picking the same thing again, making it easier to test this use case.

**Comment by ravsii** [comment] 2023-05-27 17:36
> I'll run the program like:
> 
> ```shell
> tcping fb.com 443 -r 2
> ```
Thanks, good idea

Last question: In which cases there should be output? I think 2 and 3 for sure, but what about 1?

<img width="876" alt="image" src="https://github.com/pouriyajamshidi/tcping/assets/5007271/425211b4-9b30-40dd-b5f9-67f12e001831">

**Comment by pouriyajamshidi** [comment] 2023-05-27 19:11
We should show the result in the `summary` output only; number 3 in your image.

**Comment by ravsii** [comment] 2023-05-27 20:17
ngl it looks a bit ugly (very lon) with ipv6 addresses
![image](https://github.com/pouriyajamshidi/tcping/assets/5007271/b3a8caa9-fdb6-4a45-8f70-d79a3230575e)

Maybe split it into multiple strings, like
```
IP address was changed at 2023-23-23....
2a03:2880:f113:81:face:b00c:0:25de -> 2a03:2880:f113:81:face:b00c:0:25de
```

Also this is probably not working as intended, as it tried to resolve using the same ip twice (sometimes more) in a row. I dont know much about networking, so could be wrong here.

> I have written `retryResolve` function to randomly pick an address and it **`should avoid picking the same thing again`**, ....

```bash
❯ host fb.com
fb.com has address 157.240.205.35
fb.com has IPv6 address 2a03:2880:f113:81:face:b00c:0:25de
fb.com mail is handled by 10 mxb-00082601.gslb.pphosted.com.
fb.com mail is handled by 10 mxa-00082601.gslb.pphosted.com.
```
![image](https://github.com/pouriyajamshidi/tcping/assets/5007271/44ed6cbd-41e3-4ffc-bc88-853a7a56e4c9)

_(don't mind the amount of IPs in `host`, facebook is just banned in my country)_

**Comment by pouriyajamshidi** [comment] 2023-05-28 10:42
Maybe something like:

```text
IP address changes:
 from abc to xyz at 00:00:00
 from xyz to abc at 00:20:00
```

if the new and old IP addresses are the same, we do not report anything. Because nothing was changed.

hmmm, I chose FB because they had a lotta IP addresses. Not sure what websites in your country are having multiple IP addresses but usually the popular ones like `yandex` or `vk` should have multiple ones.

Try the `host` command similar to my example and see if we get lucky?

**Comment by ravsii** [comment] 2023-05-28 10:54
> Maybe something like:
> 
> ```
> IP address changes:
>  from abc to xyz at 00:00:00
>  from xyz to abc at 00:20:00
> ```

Yeah, let's try

> if the new and old IP addresses are the same, we do not report anything. Because nothing was changed.

Of course.
 
> hmmm, I chose FB because they had a lotta IP addresses. Not sure what websites in your country are having multiple IP addresses but usually the popular ones like `yandex` or `vk` should have multiple ones.

Yeah, could work as well, but I just used VPN, so that's not a problem.

What I meant is: it tried to resolve `fb.com` and gave me the **same** ipv6 address twice in the row, but you said tcping shouldn't try/check the same address more than once. As I already said, I'm not sure if it's a bug or it supposed to work this way.

Because of that, this happens (resolving into the same IP twice)
> ![image](https://user-images.githubusercontent.com/5007271/241428386-44ed6cbd-41e3-4ffc-bc88-853a7a56e4c9.png)
> ![image](https://user-images.githubusercontent.com/5007271/241428233-b3a8caa9-fdb6-4a45-8f70-d79a3230575e.png)

I think the appropriate question is: Is it supposed to work this way and it's my job to handle this, or is it a bug and resolving into the same ip twice in a row is unintended behaviour?

**Comment by pouriyajamshidi** [comment] 2023-05-28 11:19
> What I meant is: it tried to resolve fb.com and gave me the same ipv6 address twice in the row, but you said tcping shouldn't try/check the same address more than once. As I already said, I'm not sure if it's a bug or it supposed to work this way.

ah, I think you only see one IPv4 and one IPv6 address for FB which is usually the case for most resolvers. It is fine.

> I think the appropriate question is: Is it supposed to work this way and it's my job to handle this, or is it a bug and resolving into the same ip twice in a row is unintended behaviour?

This is not a bug from our end. No need to handle any special edge cases. The purpose of this issue is to just report actual changes if there are any.

**Closed** 2023-05-29 19:21 UTC
Labels: enhancement, good first issue
