### ISSUE TITLE
One failed probe prints `No response received for 0 seconds`

### ISSUE THREAD

**Issue by ravsii** [pouriyajamshidi/tcping#91] opened 2023-05-28 18:37 UTC
**Describe the bug**
When only 1 probe is failed, it prints `No response received for 0 seconds`. Works fine with 2 and more probes.

(probably) not a printer bug

**To Reproduce**
On latest master:
1. `go run . example.com 80`
2. Try to fail only 1 probe

**Expected behavior**
`No response received for 1 second`

**Screenshots**
![image](https://github.com/pouriyajamshidi/tcping/assets/5007271/1aa2e8e2-488f-43e3-8449-faa6a2446272)
![image](https://github.com/pouriyajamshidi/tcping/assets/5007271/034b5340-5837-47ad-9a18-efe1d630826c)

**Additional context**
As far as I know, almost all durations are hardcoded as `duration += time.Second` right now. My _guess_ would be that this extra second is missing somewhere.

**Comment by pouriyajamshidi** [comment] 2023-05-28 19:37
Hey @ravsii,

Indeed, this is a blocker for the next release. However, isn't it the same as the first bullet point described in #83?

**Comment by ravsii** [comment] 2023-05-28 19:42
Oh, looks like it is. Could be closed as a duplicate then, sorry.

**Comment by pouriyajamshidi** [comment] 2023-05-29 06:58
No worries mate

**Comment by pouriyajamshidi** [comment] 2023-05-29 07:01
duplicate of #83

**Closed by pouriyajamshidi** 2023-05-29 07:01 UTC
Labels: duplicate, good first issue
